# Generated by Django 4.2.16 on 2024-09-30 06:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_cartitem_cart_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f1f0fb4f-2f3b-4494-978b-56a80d9519e9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
