# Generated by Django 4.2.16 on 2024-10-12 01:43

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_adress_id_alter_cartitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products', validators=[store.validators.validate_file_size]),
        ),
    ]
