# Generated by Django 4.2.16 on 2024-10-12 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagItem',
            new_name='TaggedItem',
        ),
    ]
