# Generated by Django 4.2.16 on 2024-10-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_rename_tagitem_taggeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
